spring.cloud.stream:
  bindings:
    producer-out-0:      
          destination: numbers
    processor-in-0:      
          destination: numbers
    processor-out-0:      
          destination: sqares
    consumer-in-0:      
          destination: sqares
spring:
  cloud:
    function:
      definition: producer;processor;consumer
#Metricas
management:
  endpoints:
    web:
      exposure:
        include: metrics